# Generated by Django 4.2.4 on 2023-09-08 22:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_follow_options_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, help_text=255, max_length=128, verbose_name='Пароль'),
            preserve_default=False,
        ),
    ]
